title: Decision Advisor
subtitle: This is the subtitle
question_header: These are the questions
service_header: These are the services
chart_header: This is the chart
email_form_header: This is the email email_form
email_address: rjm2@example.com
email_name:  Rich
